spring.application.name=VIELO SmartBet
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/vielodb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Etienne27}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

logging.level.com.vielo.smartbet=INFO

# API-FOOTBALL (API-Sports)
vielo.apifootball.enabled=${APIFOOTBALL_ENABLED:true}
vielo.apifootball.base-url=${APIFOOTBALL_BASE_URL:https://v3.football.api-sports.io}
vielo.apifootball.key=${APIFOOTBALL_KEY:0fdec90cc81ae4d5a8aa558bedc8dd03}
vielo.apifootball.leagues=


# Stripe
vielo.stripe.enabled=${STRIPE_ENABLED:true}
vielo.stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_51TP48DAmHFpwYhRS50vHLyTPmeFu0sxGWuA11EMIBK8glDR7GDpfNYerSRpsNMEk9stE39hQR818ovEuAeKJ0cvd000OtgJcjF}
vielo.stripe.public-key=${STRIPE_PUBLIC_KEY:pk_test_51TP48DAmHFpwYhRSrhmLlGmAtiGGHsYqTgJnJE9lb2YBBhHCBX2I2XptWL661tnIhhMehlhjn0jgIIvA7JJxGU7I007OpzPeqC}
vielo.stripe.currency=${STRIPE_CURRENCY:usd}
vielo.stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:8080/payment/stripe/success}
vielo.stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:8080/payment/stripe/cancel}

vielo.pricing.monthly=${VIELO_PRICING_MONTHLY:9.99}
vielo.pricing.annual=${VIELO_PRICING_ANNUAL:79.99}

vielo.premium.monthly-days=${VIELO_PREMIUM_MONTHLY_DAYS:30}
vielo.premium.annual-days=${VIELO_PREMIUM_ANNUAL_DAYS:365}

vielo.oddsapi.enabled=${ODDS_API_ENABLED:true}
vielo.oddsapi.base-url=${ODDS_API_BASE_URL:https://api.the-odds-api.com}
vielo.oddsapi.key=${ODDS_API_KEY:3352c30dccf561db3bbc1b0bb79af44f}
vielo.oddsapi.regions=${ODDS_API_REGIONS:uk,eu}
vielo.oddsapi.markets=${ODDS_API_MARKETS:h2h,totals}
vielo.oddsapi.max-kickoff-diff-minutes=${ODDS_API_MAX_KICKOFF_DIFF_MINUTES:90}

vielo.free-tips-per-day=${VIELO_FREE_TIPS_PER_DAY:5}

vielo.demo.enabled=${VIELO_DEMO_ENABLED:false}
vielo.max-predictions-per-day=${VIELO_MAX_PREDICTIONS_PER_DAY:10}
